[package]
name = "kohnert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.3"
itertools = "0.10.5"
smallvec = "1.10.0"
tinyset = "0.4.15"
